name: Build APK
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev phone_id openssl zip unzip zlib1g-dev

      - name: Build APK with Buildozer
        uses: ArtemShatalov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          repository_root: .
